### ISSUE TITLE
blog.gitter.im code snippets on one line

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/gitter#1110]
It looks like the blog is rendering out code blocks on one line. See http://blog.gitter.im/2014/02/12/monitoring-upstart-processes/ for an example.

**Comment by MadLittleMods** [comment]
Looks like we just need to add:

```css
code {
  white-space: pre;
}
```
