### ISSUE TITLE
Topics with links are broken

### ISSUE THREAD

**Issue by Haroenv** [gitterHQ/gitter#1199]
links inside it somehow get pushed on multiple lines

![](https://i.imgur.com/t0E8cin.png)

![](https://i.imgur.com/7o06kJW.png)

Browsers:

The troubling css is:

```css
.chat-header__topic { /* line 6690 */
  display: -webkit-flex
  display: flex;
}
```

- [x] Safari 9.1
- [ ] Chrome Canary 51
